# Generated by Django 3.2 on 2022-12-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_avtive',
            new_name='is_active',
        ),
    ]
