# Generated by Django 3.2 on 2022-12-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_is_avtive_cartitem_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_active',
        ),
    ]
